maxmin = [770e-9, 935e-9];
a2range = [-1e-10, 1e-10];
ascan = double(bscan(75, :));

result = generate_dispersion_luts(ascan, maxmin, ...
    'A2Range', a2range, ...
    'NumSteps', 301, ...
    'A3', 0, ...
    'FracBits', 17, ...
    'LutWidth', 18, ...
    'Metric', 'peak_to_energy', ...
    'DebugPlots', true);

disp(result.a2_best);
cos_lut=result.cos_lut;
sin_lut=result.sin_lut;